### ISSUE TITLE
Where can turn the parameter to solve the "out of memory" problem?

### ISSUE THREAD

**Issue by SongJiaxinHIT** [lmb-freiburg/flownet2#118]
When I run the demo,an error occur is

F0404 14:23:42.628688 24692 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
I know this is due to the small memory of my graphics card.Is there some parameter like yaml file to solve this problem?Thanks a lot.

**Comment by nikolausmayer** [comment]
You can use smaller input images, or a smaller model: FlowNet2-c needs less memory than FlowNet2-C, and FlowNet2-CS needs less memory than FlowNet2-CSS.

You could also rewrite the runtime script to execute the network layer-by-layer instead of loading the whole thing into memory at once. However, that'll be much slower, and (I imagine) also quite a bit of work.

Other than that, you'll need retraining.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
