### ISSUE TITLE
Question about FlyingData3D background depth

### ISSUE THREAD

**Issue by shopkauf** [lmb-freiburg/flownet2#122]
May I ask if the background of each image is planar or does it contain complicated depth? In the paper, it says "The base of each scene is a large textured ground plane", so it seems to be planar. But it also says "We generated 200 static background objects". 
Thanks.

**Comment by nikolausmayer** [comment]
The 3D scenes contain:
- a flat texture plane that serves as "ground" reference
- a hemispherical textured skydome
- 200 static objects (simple geometric solids) placed somewhere on the flat ground (we refer to them as "background" because they are further away from the camera than the moving foreground objects)
- a random number of dynamic foreground objects with complex geometry

Here's an example. The background is simple geometric shapes, but not just flat. Whether that makes for "complicated" depth is in the eye of the beholder :)

![finalpass_0006_l](https://user-images.githubusercontent.com/7045923/38482888-519f3272-3bd1-11e8-9c97-768b39de0eb7.jpg)
![disp_0006_l](https://user-images.githubusercontent.com/7045923/38482893-55f39d5e-3bd1-11e8-8e94-2dc6b7e6cd4c.jpg)

**Comment by shopkauf** [comment]
Thanks so much for the quick reply. 
Let's say, there is a flat area in the background that is textured as tree leaves. This could wrongly teach the algorithm that leaves don't have depth info. So, I guess one must be careful in choosing the texture for the flat pixels?

**Comment by nikolausmayer** [comment]
That is definitely valid if you are doing depth-from-single-image.

In our setting, I'd actually claim that the opposite is true: If all our flat object had "flat" textures, then the network would fail e.g. when looking at a magazine or a poster or a painting—it would see structure and think "oh there's structure here, so this thing can't be flat!".

We try to remove as much bias as possible. Our dataset contains untextured and textured simple and complex objects. To perform well on both complex geometry and flat objects with "leaves" textures, the network must learn to infer depth from actual stereo matching instead of priors.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
