### ISSUE TITLE
How make a demon

### ISSUE THREAD

**Issue by BluebirdStory** [lmb-freiburg/flownet2#174]
My mentor now wants me to make a demo based on your model and released code, it probably will be like this: there should be a interface with two rectangles in it, one for  showing currently captured frames, and the other for the flow predicted. So here is the issue: how can I accomplish it? I mean, should I write the C++ code based on your python version script run-flownet.py? or you have done these work before and I refer to them directly? Many thanks!!!!

**Comment by BluebirdStory** [comment]
I am a fresh graduate student that majored in applied math during undergraduate years, so when it comes to project problem, I am really a green hand. Looking forward to your reply, thank you sooooo much!!

**Comment by nikolausmayer** [comment]
The easiest approach is probably to adapt the code from "run-flownet.py"; instead of reading images from files, you can use OpenCV functions to grab webcam images and display network inputs and outputs. For the conversion from optical flow to a color image, check the reference code in http://vision.middlebury.edu/flow/code/flow-code.zip (unfortunately it's only C++, but the code is simple).

**Comment by BluebirdStory** [comment]
@nikolausmayer Thank you!!!
