### ISSUE TITLE
How does the network work on grayscale images when it is trained on colored images?

### ISSUE THREAD

**Issue by adhara123007** [lmb-freiburg/flownet2#190]
This is a very generic question and help with my understanding of the working is appreciated. How is the network able to give good results on grayscale images (with no color channels) when it is trained on colored images ? In other words, how do the 3d convolutional filters work when the image is grayscale? How do the trained weights of a 3D filter work on grayscale images?

**Comment by nikolausmayer** [comment]
In my opinion, "grayscale" images are just a special case of color images, so a lot of the learned features work for grayscale as well as for color. You are only losing priors for e.g. green plants.
I've used DispNet for grayscale images before, and it's very resilient to that (although my inputs were technically 3-channel grayscale images).

I don't think we have true 3D convolutions in FlowNet2? But after the first few preprocessing layers, the number of channels is fixed anyway, so that _should_ also be fine (if I understand you correctly).
