### ISSUE TITLE
About 2 Flyingthings-3D dataset

### ISSUE THREAD

**Issue by WormCoder** [lmb-freiburg/flownet2#196]
I found two flyingthings-3D dataset in your page (https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html)

And I downloaded the "DispNet/FlowNet2.0 dataset subsets", which has images about 35G.  
In your paper, it seems that you used the other one, which has images about 37G.
What's the difference between the two datasets? To train flownet2, must I download the other one? It's really large and long time for downloading. :)

**Comment by nikolausmayer** [comment]
The "subset" datasets represent what we used to train FlowNet2. They omit some very hard samples.

The original datasets have significantly more data. This could also be of use.


To reproduce our FlowNet2, use the "subset" datasets.

**Comment by WormCoder** [comment]
@nikolausmayer Thanks for your reply.
I am new to optical flow and confused about the data. I found the folders, left and right in the Image_clean folder of "subset" dataset. What's the difference between the right and left? And Which one should be used for training?

"val/image_clean/left/0000108.png"  and  "val/image_clean/left/0000109.png" are from two different videos, so what's "val/flow/left/into_future/0000108.flo" is for?

**Comment by nikolausmayer** [comment]
"left" and "right" are stereo views.

You could use `val/flow/left/into_future/0000108.flo` for future flow prediction, but for optical flow training it is generally not useful. We just include it because it is available.

I added information about the lengths of individual sub-videos to the [datasets page](https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html).

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
