### ISSUE TITLE
Generating .prototxt files

### ISSUE THREAD

**Issue by kindloaf** [lmb-freiburg/flownet2#206]
Where can I find the script to generate the .prototxt files, e.g., models/FlowNet2-S/FlowNet2-S_train.prototxt.template?

**Comment by nikolausmayer** [comment]
We do not provide a script to generate the training files, but they follow the same structure as the deploy files (with crops instead of resampling).

For deploy files, you should be able to adapt [the runscript from our Docker version](https://github.com/lmb-freiburg/flownet2-docker/blob/master/FN2_run-flownet-docker.py#L99).

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
