### ISSUE TITLE
Confused about the FlyingThings3d dataset

### ISSUE THREAD

**Issue by lesurp** [lmb-freiburg/flownet2#210]
Hi,

I'm trying to generate my own `FlyingChairs_release.list` but for the FlyingThings3d dataset (`FlyingThings3D_release.list`), however I'm slightly confused. What are the two frames corresponding each flow groundtruth?

In the FlyingChairs dataset, the matching is rather obvious:

```
FlyingChairs_release/data/00001_img1.ppm
FlyingChairs_release/data/00001_img2.ppm
FlyingChairs_release/data/00001_flow.flo
```

But for the FlyingThings3D, I have:
```
frames_cleanpass/TRAIN/A/0000/left/0006.png
optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0006_L.pfm
```

What image pair does `OpticalFlowIntoFuture_0006_L.pfm` correspond to? Is it between `0006.png` and `0007.png`? That doesn't make sense, because the number of pfm files is the same as the number of images :<

Thanks!
Paul

**Comment by nikolausmayer** [comment]
> Is it between 0006.png and 0007.png?

Yes, exactly. Your confusion is understandable; the raw dataset contains flow groundtruth even for the "edge" frames of a sequence, but if you want to do supervised training, you should ignore all `0015` "forward" flows and all `0006` "backward" flows (because the corresponding images 0016 and 0005 are not in the dataset).

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
