### ISSUE TITLE
Models from download-model.sh

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [lmb-freiburg/flownet2#221]
Hi,

What are the different models that are being downloaded using download-models.sh?
Flownet2-KITTI might be for the model trained on KITTI dataset
Flownet2-SINTEL might be for the model trained on SINTEL dataset
Flownet2, Flownet2-c, Flownet2-C, Flownet2-cs, flownet2-CS, Flownet2-css, Flownet2-CSS, Flownet2-css-ft-sd, Flownet2-CSS-t-sd, Flownet2-s, Flownet2-S, Flownet2-SD, Flownet2-SS, Flownet2-ss, Flownet2-sss:  What are all these models for? What are the datasets used for their training?

**Comment by nikolausmayer** [comment]
KITTI and SINTEL are what they seem to be 🙂 
The other models are described (or at least listed) in Section 4.2 and Table 3 in [the FlowNet2.0 paper](https://ieeexplore.ieee.org/document/8099662/). In short, they are intermediate networks in the network-stacking process and/or reduced-capacity models.
If any model is missing, its name should give hints about what the model is. In any case, any model not explicitly explained is just included for completeness, not because it is particularly great.

**Comment by Diksha-Moolchandani** [comment]
Thanks for the prompt reply. 
This is what I understood:
1.  FlowNet2-KITTI and Flownet2-Sintel have the same architecture as in Figure 2 but are trained on different datasets. 
2. FlowNet2-S and FlowNet2-C are equivalent to the two flownet architectures: flownetsimple and flownetcorr proposed in the flownet paper.
3. Is any of the models equivalent to DispNet ? Can Flownet2-S be said equivalent to DispNet?

**Comment by nikolausmayer** [comment]
1. I believe so, yes, but you should double-check the FlowNet2.0 paper to make sure.
2. Yes. 
3. The DispNet has additional convolutional layers in the decoder that aid smoothing, and its decoder is "longer" to output a higher resolution, but otherwise they are equivalent.

**Comment by Diksha-Moolchandani** [comment]
Thanks
