### ISSUE TITLE
Dataloader for loading images

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [lmb-freiburg/flownet2#222]
Hi,

Are you aware of some dataloader that can be used to speed up the image loading process, i wanted to run this for the entire sceneflow monkaa dataset? I know the one in pytorch but I am unsure of its usability in a caffe based code such as flownet2 and loading+reading single image takes a lot of time to cover the entire monkaa dataset.

**Comment by nikolausmayer** [comment]
The main speed bottleneck with our release code is not the data loading, but the network being reinitialized for every input sample (because we cannot assume that all inputs have the same dimensions). You can change the Python code to reuse the network for all samples, see https://github.com/lmb-freiburg/flownet2/issues/105.

**Comment by Diksha-Moolchandani** [comment]
Thanks
