### ISSUE TITLE
Issue in compute_image_mean.o

### ISSUE THREAD

**Issue by letatanu** [lmb-freiburg/flownet2#64]
Hi, I'm getting this error when compiling Caffe in Flownet2:

> CXX/LD -o .build_release/tools/convert_imageset_and_flow.bin
.build_release/tools/compute_image_mean.o: In function `_GLOBAL__sub_I_compute_image_mean.cpp':
compute_image_mean.cpp:(.text.startup+0x16d): undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
CXX/LD -o .build_release/tools/net_speed_benchmark.bin
collect2: error: ld returned 1 exit status
Makefile:620: recipe for target '.build_release/tools/compute_image_mean.bin' failed

I did some research, they recommend using cmake. However, there's no cmake folder in Flownet2's Caffe. Any idea?

**Comment by nikolausmayer** [comment]
This issue is due to your system setup, not our code. We understand that this repository is not trivial to use, and we regret this, but this is only research code, not a consumer-grade product. 

For ease of use, please check out our Docker image. It takes care of all the compilation and you can start working with FlowNet right away: https://github.com/lmb-freiburg/flownet2-docker

If you do not have experience in compilation, I recommend getting help from someone (an admin, a coworker, or another student) who can show you how to understand compilation and linker errors, and how to find files on your machine.

**Comment by letatanu** [comment]
Thank you. The reason I posted my issue is to help other people getting the same problem. 
I solved my issue by adding gflags path to Makefile.config.
