### ISSUE TITLE
How to warp an image with optical flow?

### ISSUE THREAD

**Issue by Feiyue-Peng** [lmb-freiburg/flownet2#89]
Hi,
  I couldn't find your code about how to warp an image with the optical flow, I would appreciate it if tell me.
  And I tried to warp the image with warped(:, :, i, j) = interp2(Xi, Yi, imgs(:, :, i, j), curX, curY, 'spline', 0) in matlab2017a that you have mentioned in the paper.  But I got the following result where the original person still remained in the image. How should I remove the former action from the warped image?
![1](https://user-images.githubusercontent.com/26792806/33051724-51c4c692-cea6-11e7-8d94-5156f648351c.png)
Yours,
Daisy

**Comment by nikolausmayer** [comment]
Hi,
the warping code is in https://github.com/lmb-freiburg/flownet2/blob/master/src/caffe/layers/flow_warp_layer.cpp and https://github.com/lmb-freiburg/flownet2/blob/master/src/caffe/layers/flow_warp_layer.cu
These "double images" are normal in forward warping (so I guess that is what `interp2` does). You can either mask out pixels to which no flow vector points, or use backward warping instead (i.e. instead of forward-warping the first image with the "first -> second" flow, backward-warp it with the "second -> first" flow). But note that while backward warping does not have the "double images", it may show other artifacts.

**Comment by Feiyue-Peng** [comment]
Thank you for your attention. I think the interp2 does the backward-warping and I have done experiments to verify it. When I use interp2 to warp image with optical flow[CeLiu], it turns out no "double images", so I think maybe it is the problem of optical flow.
Thanks.

**Comment by bkvie** [comment]
In case of occlusion the flowmap will not map pixels to the shifted location, leaving parts of the image intact. This creates a duplication, a common problem in flow warping.

**Comment by WormCoder** [comment]
@Feiyue-Peng Do you know how to perform forward flow warpping?
